apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer   # make this accessible from outside (e.g. browser, Postman)
---

# Service for Dealer Service (internal only)
apiVersion: v1
kind: Service
metadata:
  name: dealer-service
spec:
  selector:
    app: dealer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP       # internal communication only

---

# Service for Invoice Service (internal only)
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
spec:
  selector:
    app: invoice-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 